spring.datasource.url=jdbc:postgresql://localhost:5432/${PROD_DATABASE_NAME}
spring.datasource.username=${PROD_DATABASE_USERNAME}
spring.datasource.password=${PROD_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

logging.level.io.github.khaytul.illia.book_catalogue_api=INFO