spring.datasource.url=jdbc:postgresql://localhost:5433/${DEV_DATABASE_NAME}
spring.datasource.username=${DEV_DATABASE_USERNAME}
spring.datasource.password=${DEV_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.enabled=true
springdoc.override-with-generic-response=false

logging.level.io.github.khaytul.illia.book_catalogue_api=DEBUG