spring.application.name=book-catalogue-api

server.port=8080

spring.profiles.active=dev

spring.app.retries.update-book=3

spring.flyway.locations=classpath:db/migration/{vendor}

spring.mvc.servlet.path=/api/v1

spring.data.web.pageable.max-size=100

spring.web.format.date=iso
spring.web.format.date-time=iso
spring.web.format.time=iso

logging.level.root=INFO
