spring.application.name=book-catalogue-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/book-catalogue
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.web.pageable.max-size=100

spring.web.format.date=iso
spring.web.format.date-time=iso
spring.web.format.time=iso

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.enabled=true
springdoc.override-with-generic-response=false

logging.level.root=INFO
logging.level.io.github.khaytul.illia.book_catalogue_api=DEBUG
