CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    author VARCHAR(255) NOT NULL,
    pages INTEGER,
    release_date DATE,
    version INTEGER,
    
    PRIMARY KEY (id),

    CONSTRAINT unique_title_per_author UNIQUE (title, author)
);