create table users
(
    id       bigint generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,

    primary key (id),

    constraint unique_username unique (username)
);