create table books (
    id bigint generated by default as identity,
    title varchar(255) not null,
    description text,
    author varchar(255) not null,
    pages integer,
    release_date date,
    version integer,

    primary key (id),

    constraint unique_title_per_author unique (title, author)
);